language: python
python:
    - 2.7
    - 3.3
before_install:
    - pip install numpy
    - pip install sphinx
    - pip install sphinxcontrib-napoleon
script:
    - (cd $TRAVIS_BUILD_DIR && make html)
    - python -m unittest discover
